# Generated by Django 3.0.7 on 2020-09-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=55)),
                ('last', models.CharField(default='', max_length=55)),
                ('state', models.CharField(default='', max_length=255)),
                ('age', models.CharField(default='', max_length=15)),
                ('sex', models.CharField(default='', max_length=15)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv_aid', models.CharField(max_length=255, null='True')),
                ('hepatitis_B', models.CharField(max_length=255, null='True')),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stphohapp.Patient_info')),
            ],
        ),
    ]
