# Generated by Django 3.0.7 on 2020-09-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stphohapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='age',
            field=models.IntegerField(),
        ),
    ]
