# Generated by Django 3.0.7 on 2020-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stphohapp', '0002_auto_20200913_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='', max_length=55)),
                ('last', models.CharField(default='', max_length=55)),
                ('state', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(default='', max_length=15)),
                ('phone', models.CharField(default='', max_length=15)),
                ('hiv_aid_test', models.CharField(max_length=100)),
                ('hepatitis_B_test', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='test_result',
            name='patient_info',
        ),
        migrations.DeleteModel(
            name='Patient_info',
        ),
        migrations.DeleteModel(
            name='test_result',
        ),
    ]
