# Generated by Django 3.0.7 on 2020-09-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stphohapp', '0003_auto_20200913_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='', max_length=15),
        ),
    ]
