# Generated by Django 3.0.7 on 2020-09-13 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stphohapp', '0004_auto_20200913_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv_aid_test', models.CharField(max_length=100)),
                ('hepatitis_B_test', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hepatitis_B_test',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hiv_aid_test',
        ),
        migrations.AddField(
            model_name='patient',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stphohapp.Result'),
        ),
    ]
